### ISSUE TITLE
Add 'Supervisor' part to the Assignment section of a Personnel file

### ISSUE THREAD

**Issue by Holidayy95** [forumify/forumify-perscom-plugin#11]
Add a 'Supervisor' part to the Assignment section, that hyper links to the soldiers Personnel file that you add there, example below;

https://i.imgur.com/C6qXVmd.png

**Comment by jannes-io** [comment]
Hi @Holidayy95 ,

Thanks for the suggestion, we've been asking for a "supervisor" feature in PERSCOM.io for a while.

Perhaps where we can assign a supervisor to a unit, and then everyone assigned to that unit gets the same supervisor so it's on a higher level instead of individually on user level?

Either way, it's not something that PERSCOM.io offers at this point in time.

![image](https://github.com/user-attachments/assets/3e9ce996-820f-456b-beb8-a3f6b56a95b3)

Feel free to re-open or recreate this issue when PERSCOM.io has this data available in their API.
